--Questions to answer with SQL


--Q1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer_shopping_behaviour
group by gender


--Q2. Which customers used  a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_shopping_behaviour
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_shopping_behaviour)


--Q3. Which as the top 5 products with the highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer_shopping_behaviour
group by item_purchased
order by avg(review_rating) DESC
limit 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2) as avg_spend,
from customer_shopping_behaviour
where shipping_type IN ('Standard','Express')
group by shipping_type
order by avg_spend desc


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select
subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customer_shopping_behaviour
group by subscription_status
order by total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select
item_purchased,
ROUND(100 * SUM(
CASE 
	WHEN discount_applied = 'Yes' THEN 1 
	ELSE 0
	END
)/COUNT(*),2) as discount_rate
from customer_shopping_behaviour
group by item_purchased 
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning and Loyal, based on their total number of previous purchases, 
--and show the count of each segment.
with customer_type as (
select 
customer_id,
previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases between 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END as loyalty_rating
from customer_shopping_behaviour
)
select loyalty_rating, count(*) as "Number of Customers"
from customer_type
group by loyalty_rating


--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer_shopping_behaviour
group by category, item_purchased
)

Select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3


--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 
subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behaviour
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue
select
age_group,
SUM(purchase_amount) as total_revenue
from customer_shopping_behaviour
group by age_group
order by total_revenue DESC